### ISSUE TITLE
Package structure

### ISSUE THREAD

**Issue by jordanterry** [jordanterry/Espresso-Examples#10]
The package name of the project isn't very well named so it needs to be renamed.
test.nice.testproject -> uk.co.jordanterry.espressoexamples

**Comment by jordanterry** [comment]
@EGecius I'm not going merge this just yet, but it will be interesting to see what you think about the renaming of the packages. I changed it to my domain and then the name of the project so __uk.co.jordanterry.espressoexamples__ I felt it was better than __test.nice.testproject__. If you can think of another package name that would be more appropriate let me know!

**Comment by EGecius** [comment]
sounds good to me. Thanks for asking. Feel free to close it.
