### ISSUE TITLE
Contributions welcome?

### ISSUE THREAD

**Issue by EGecius** [jordanterry/Espresso-Examples#2]
Hi there,

I am very happy to contribute to this project such as:
update dependencies
use ActivityTestRule instead of ActivityInstrumentationTestCase2
tidy up code

Would any of that be welcome? If so, any preferences? I am quite keen to move fast, so please let me know. I will fork the project if not. No worries.

Thanks

Egis

**Comment by jordanterry** [comment]
Hi! Contributions are more than welcome. I've been working on an update to this as I'm aware it is a bit out of date so anything you can contribute would be awesome.
