### ISSUE TITLE
Use ActivityRule

### ISSUE THREAD

**Issue by EGecius** [jordanterry/Espresso-Examples#3]
Using ActivityRule allows running Espresso tests in any class, thus not requiring to extend Android's TestCase classes.

I have implemented this already on my local machine but am denied access when trying to push my feature branch. Do I need any special permissions?

**Comment by jordanterry** [comment]
I'm a bit new to actually owning a repo people are using. But I've added you as a collaborator to this repo, so I hope you can contribute now!

**Comment by EGecius** [comment]
thanks. I just pushed my branch successfully.
